# Generated by Django 4.2.2 on 2023-08-04 14:35
# https://stackoverflow.com/questions/25924858/django-1-7-migrate-gets-error-table-already-exists
# https://stackoverflow.com/questions/29902366/django-migration-is-not-applying-the-migration-changes
# https://blog.logrocket.com/using-react-django-create-app-tutorial/

from django.db import migrations

def create_data(apps, schema_editor):
    Users = apps.get_model('userAuth', 'Users')
    # Users ^ is user model and 
    Users(name = "abc", email = "abc@gmail.com", password = "abc", gender = "M").save()

class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_userAuth'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]

